# LB nodes subnet = 10.0.1.0/24
# K8s master nodes subnet = 10.0.3.0/24
# K8s worker nodes subnet = 10.0.5.0/24

LB_COUNT = 2
K8S_MASTER_COUNT = 3
K8S_WORKER_COUNT = 3

IMAGE = "bento/ubuntu-22.04"

Vagrant.configure("2") do |config|

    (1..LB_COUNT).each do |i|
        config.vm.define "lb-control-0#{i}" do |node|
        node.vm.box = IMAGE
        node.vm.hostname = "lb-control-0#{i}"
        node.vm.network  :private_network, ip: "10.0.1.#{i-1+11}"
        node.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "512"
            vb.cpus = 1
            vb.name = "lb-control-0#{i}"
        end
        node.ssh.username = "vagrant"
        node.vm.provision "shell", name: "Authentification", path: "./provision-scripts/auth.sh"
        end
    end

  (1..K8S_MASTER_COUNT).each do |i|
        config.vm.define "k8s-master-0#{i}" do |node|
        node.vm.box = IMAGE
        node.vm.hostname = "k8s-master-0#{i}"
        node.vm.network  :private_network, ip: "10.0.3.#{i-1+31}"
        node.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "2048"
            vb.cpus = 2
            vb.name = "k8s-master-0#{i}"
        end
        node.ssh.username = "vagrant"
        node.vm.provision "shell", name: "Authentification", path: "./provision-scripts/auth.sh"
        end
    end

    (1..K8S_WORKER_COUNT).each do |i|
        config.vm.define "k8s-worker-0#{i}" do |node|
        node.vm.box = IMAGE
        node.vm.hostname = "k8s-worker-0#{i}"
        node.vm.network  :private_network, ip: "10.0.5.#{i-1+51}"
        node.vm.provider "virtualbox" do |vb|
            vb.gui = false
            vb.memory = "512"
            vb.cpus = 2
            vb.name = "k8s-worker-0#{i}"
        end
        node.ssh.username = "vagrant"
        node.vm.provision "shell", name: "Authentification", path: "./provision-scripts/auth.sh"
        end
    end

end
